### PR TITLE
@due now uses bracket matching with recursive regex.

### PR DESCRIPTION
**Pull request by oliverwilliams84**
Requires new dependancy but allows full use of all regex features (so likely worth?)

There's probably other regex's that need updating but can't be bothered to find them all. Guessing it's all of them?

The funky regex on line 50 doesn't work with the regex package so it's still using both re and regex. Not perfect but I don't really understand what's happening in that regex at all

### CODE REVIEW

**Comment by oliverwilliams84** [comment]
Does this even need to be recursive regex? Could just match the first close bracket we encounter.

IMO the best solution is the outer brackets are matched and any inner brackets are ignored so @due(01(1)) would match. It's a erroneous case there but it's technically correct?

**Comment by vovkkk** [comment]
regex dependency is restricted to ST3, so we either should avoid it or properly fall back on ST2.

**Comment by oliverwilliams84** [comment]
The re module is severely limited - no recursion, no atomic groups, no subroutines. It's needed upgrading for the last 10+ years?

Regex package is only 200kb, could bundle it in with the plugin. Otherwise can try find the regex parser sublime use's but getting it to work on given strings might be interesting as I think the API functions we get are linked to the full view.

**Comment by vovkkk** [comment]
> could bundle it in with the plugin

Will you compile it for every OS and architecture? No-no, bundling is not an option (it will be much more than 200kB after all; plus maintenance burden);
we could (if you’re insisting on regex module) either ask/help facelessuser to add support for ST2 or make separate dependency which would be restricted to ST2 or just make a fall back (i.e. another implementation, without regex, with different behaviour) for ST2.
Or [preferably] find out a way to achieve desirable behaviour without any dependencies, if it is possible ofc.

**Comment by oliverwilliams84** [comment]
I believe https://regex101.com/r/MC36sr/3 does it. Doesn't match brackets and only works on perfectly formatted dates (basically anything the expand will work on)

**Comment by vovkkk** [comment]
> only works on perfectly formatted dates

This is unnecessary, regexp that we need must match anything within parentheses.



> https://regex101.com/r/MC36sr/3

The first line must be matched (i.e. `@due(tes(aa(t)t)) (aaa) aaaa`, the expected result of expansion for such tag will be a timestamp of current moment, i.e. today or now) the only question which text here is a part of tag’s parentheses and which is not a part.
_Common sense_ suggests that tag is `@due(tes(aa(t)t))` and `(aaa) aaaa` is not a part of the tag.

**Comment by oliverwilliams84** [comment]
The parser itself use's the same regex to determine how to build the extended date. If it fails the 
>https://regex101.com/r/MC36sr/4
match then it will fail to preview the expanded string -> result is the same.

Can't match the brackets without recursion. https://regex101.com/r/HzHGNj/6 show how this would work with a full regex parser. 

Sublime scope syntax (meta.tag.todo etc) has the ability to do this. Could we offload all of this matching into a new scope "meta.tag.date" and check for the scope name like it already does for "meta.tag.todo"?

**Comment by vovkkk** [comment]
Yes, using a scope is an option, however, it has downsides which can [and should] be work around e.g. our calendar does extract parenthesis https://github.com/aziz/PlainTasks/blob/master/PlainTasksDates.py#L542-L564

Also, html converter extracts scopes https://github.com/aziz/PlainTasks/blob/master/PlainTasksToHTML.py#L286-L330

**Comment by oliverwilliams84** [comment]
What will I need to be careful about when adding a scope, if that is the only way? It's not immediately obvious what those functions do

**Comment by vovkkk** [comment]
Well, you should be careful about using `view.extract_scope` method, because its output may vary depending on input, i.e. it may return different result for starting point of a scope and for ending point, also keep in mind that presence of phantom may affect this method https://github.com/SublimeTextIssues/Core/issues/1497

**Comment by oliverwilliams84** [comment]
Where is the calendar supposed to input the date? Currently, inserting a date between the two tags here:
`@tagsaat(123) (aaa) aaa Testing work lalala @test`
gives:
`@tagsaat(13-05-17 20:59) @test`

Is it intended to overwrite all the middle text or should it do:
`@tagsaat(13-05-17 20:59) (aaa) aaa Testing work lalala @test`

**Comment by vovkkk** [comment]
It should replace only `123`, given you have cursor on it.
And it does work this way if you use _recommended workaround_ from #329, i.e. use non-breaking whitespace or comma to separate tag and and following normal text.

**Comment by oliverwilliams84** [comment]
#341 fixes that issue and should be pullable if I mirror the changes across to the tmLanguage file:
woo image
I have a more up to date version of the code that matches better in a different branch.

This doesn't effect the calender as that requires use of the "re" module / can't use recursive regex to match brackets.

**Pull request closed without merging**
